### ISSUE TITLE
Alternatives to WD-40

### ISSUE THREAD

**Issue by Acecool** [LucidVR/lucidgloves-hardware#4]
WD-40 is a bit messy, and leaves an odor, one alternative is graphite. It can be applied easily.. It is conductive, but the spool can be designed to hold a bit in excess without spilling out, apply less liberally or shake out excess before final assembly..

They sell graphite in powder form for this very thing, and it lasts a long time.

Another option, could be to print the spools in a wood based filament, sand smooth and use beeswax - this is what furniture makers did way back when, or when wood on wood drawers were becoming harder to overcome static friction or sticking because of moisture / humidity. This makes the wood slide incredibly smooth, and most people with a piece of sandpaper can feel minute differences and work them out very easily. This method can easily last an incredible amount of time for furniture used regularly - but as this has a higher use-rate it would need to be tested.

-- I would just recommend a few alternatives, and what to expect by using each one.

**Comment by lucas-vrtech** [comment]
Yeah, the tricky thing is that the lube is meant to go inside the potentiometers, and not on the 3d printed part. So I'm not 100% sure how beeswax/graphite would behave inside the pot itself. I added some alternatives people in the server have tried other than WD-40, feel free to DM me if you try something that works well :)
